"""
Generate the clock app's kanji rain font.

The same 1-bit format and the same 16x32 cell as ngl_font_small, so the rain
grid can mix these glyphs with the system font's latin ones without knowing
which is which - it picks a font per cell and the geometry is identical.

Two things differ from genfont.py, and both follow from kanji being square:

  - the glyph is rasterised into a 16x16 box and centred in the 32-tall cell,
    rather than filling it. A kanji stretched to twice its width is not a
    kanji, and the leftover leading is what rain wants anyway.

  - the codepoints are not contiguous, so the output is indexed from 128
    rather than from the character's own value. A rain cell holds 128..255 for
    a kanji and an ordinary code for latin, which is also how the app decides
    which font to draw it with.

The set is chosen for legibility at 16px, not for meaning: everything here is
under about nine strokes, because anything denser is mud at this size. Elements,
weather, numerals, directions - the vocabulary a clock would know.

    python tools/genkanji/genkanji.py C:/Windows/Fonts/msgothic.ttc \\
           apps/clock/main/clock_kanji.c

The output is checked in, so a normal `idf.py build` never runs this.
"""
import sys
from PIL import Image, ImageDraw, ImageFont

CELL_W, CELL_H = 16, 32
BOX = 16                      # the square the glyph itself is drawn into

SYMBOL = "clock_font_kanji"
FIRST = 128                   # above ASCII, which is the line the app reads

KANJI = (
    "日月火水木金土"          # the weekdays, which is why they are first
    "山川田石空雨雪風雲"      # weather and ground
    "人大小中上下左右"        # the simplest shapes in the language
    "一二三四五六七八九十"    # numerals
    "生死光電力心時分年"      # a clock's own vocabulary
    "東西南北天目"
)


def fit_size(font_path, ch, box):
    """Largest point size whose glyph fits inside a box x box square."""
    best = None
    for size in range(6, box * 3):
        f = ImageFont.truetype(font_path, size)
        bb = f.getbbox(ch)
        if bb is None:
            continue
        w, h = bb[2] - bb[0], bb[3] - bb[1]
        if w <= box and h <= box:
            best = (size, f, bb)
        else:
            break
    if best is None:
        raise SystemExit(f"{ch!r} will not fit in {box}px")
    return best


def render(font_path, ch):
    """Return CELL_H rows of packed bits, glyph centred in the cell."""
    size, font, bb = fit_size(font_path, ch, BOX)
    img = Image.new("L", (CELL_W, CELL_H), 0)
    gw, gh = bb[2] - bb[0], bb[3] - bb[1]
    # getbbox is relative to the drawing origin, so subtracting it trims the
    # glyph's own bearing; what is left is centred in the cell.
    ox = (CELL_W - gw) // 2 - bb[0]
    oy = (CELL_H - gh) // 2 - bb[1]
    ImageDraw.Draw(img).text((ox, oy), ch, fill=255, font=font)

    px = img.load()
    bpr = (CELL_W + 7) // 8
    out = []
    for y in range(CELL_H):
        for b in range(bpr):
            byte = 0
            for bit in range(8):
                x = b * 8 + bit
                if x < CELL_W and px[x, y] >= 110:
                    byte |= 0x80 >> bit
            out.append(byte)
    return size, bpr, out


def main():
    if len(sys.argv) != 3:
        raise SystemExit(__doc__)
    ttf, out_path = sys.argv[1], sys.argv[2]

    last = FIRST + len(KANJI) - 1
    if last > 255:
        raise SystemExit(f"{len(KANJI)} glyphs runs past code 255, which is as "
                         f"wide as a 1-bit font's index gets")

    parts = [
        "/*\n * GENERATED by tools/genkanji/genkanji.py - do not edit.\n"
        f" * Source face: {ttf.replace(chr(92), '/').split('/')[-1]}\n"
        f" * {len(KANJI)} glyphs in {CELL_W}x{CELL_H} cells, indexed from {FIRST}.\n"
        " */\n",
        '#include "ngl.h"\n',
        f"\nstatic const uint8_t {SYMBOL}_bits[] = {{",
    ]

    bpr = 0
    for i, ch in enumerate(KANJI):
        pt, bpr, glyph = render(ttf, ch)
        if not any(glyph):
            raise SystemExit(f"{ch!r} rasterised blank - is it in this face?")
        parts.append(f"\n    /* {FIRST + i:3d}  U+{ord(ch):04X} */ " +
                     " ".join(f"0x{b:02X}," for b in glyph))
    parts.append("\n};\n")
    parts.append(f"""
const ngl_font_t {SYMBOL} = {{
    .bits         = {SYMBOL}_bits,
    .width        = {CELL_W},
    .height       = {CELL_H},
    .bytes_per_row= {bpr},
    .first        = {FIRST},
    .last         = {last},
}};
""")

    with open(out_path, "w", encoding="utf-8", newline="\n") as f:
        f.write("".join(parts))
    print(f"{SYMBOL}: {len(KANJI)} glyphs, "
          f"{len(KANJI) * CELL_H * bpr} bytes -> {out_path}")


main()
