/* GENERATED by tools/genicons/genicons.py - do not edit. */
#pragma once
#include "ngl.h"

extern const ngl_icon_t clock_icon_sun_48;
extern const ngl_icon_t clock_icon_moon_48;
extern const ngl_icon_t clock_icon_cloudsun_48;
extern const ngl_icon_t clock_icon_cloudmoon_48;
extern const ngl_icon_t clock_icon_cloud_48;
extern const ngl_icon_t clock_icon_fog_48;
extern const ngl_icon_t clock_icon_drizzle_48;
extern const ngl_icon_t clock_icon_rain_48;
extern const ngl_icon_t clock_icon_snow_48;
extern const ngl_icon_t clock_icon_storm_48;
