"""
Generate NeOS icon bitmaps from an icon font.

Rasterises named glyphs out of a TTF icon font (FontAwesome, Google Material
Symbols, Segoe MDL2, ...) into 8-bit alpha bitmaps and emits a C file for the
ngl graphics library.

Why 8-bit alpha rather than 1-bit like the text fonts: an icon is large enough
that jagged edges are obvious, and alpha lets one bitmap be tinted to any theme
colour at draw time. A 32x32 icon costs 1 KB, which is cheap against 32 MB of
PSRAM - text fonts stay 1-bit only because there are 95 glyphs per size.

Usage:
    python tools/genicons/genicons.py tools/genicons/icons.json \\
           neos/components/ngl/src/ngl_icon_data.c

The spec file names the font, the sizes, and the glyphs. See icons.json and
this folder's README.md.

An optional "prefix" in the spec renames the symbols, which is how an app
carries its own icons instead of adding to the system set. The icon set is
deliberately not part of the ABI - ngl_icon_find() looks up the firmware's by
name - but ngl_icon_t's layout is, so an app can define icons of its own and
hand ngl_icon() a pointer to one.
"""
import json
import sys
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont


def fit_size(font_path, codepoint, cell):
    """Largest point size whose rendered glyph fits inside a cell x cell box."""
    best = None
    for size in range(6, cell * 3):
        f = ImageFont.truetype(font_path, size)
        box = f.getbbox(chr(codepoint))
        if box is None:
            continue
        w, h = box[2] - box[0], box[3] - box[1]
        if w <= cell and h <= cell:
            best = (size, f, box)
        else:
            break
    if best is None:
        raise SystemExit(f"glyph U+{codepoint:04X} will not fit in {cell}px")
    return best


def render(font_path, codepoint, cell):
    """Return `cell*cell` bytes of coverage, glyph centred in the box."""
    size, font, box = fit_size(font_path, codepoint, cell)
    img = Image.new("L", (cell, cell), 0)
    # getbbox is relative to the drawing origin, so subtract it to trim the
    # glyph's own bearing, then centre what remains.
    gw, gh = box[2] - box[0], box[3] - box[1]
    ox = (cell - gw) // 2 - box[0]
    oy = (cell - gh) // 2 - box[1]
    ImageDraw.Draw(img).text((ox, oy), chr(codepoint), fill=255, font=font)
    return size, bytes(img.getdata())


def main():
    if len(sys.argv) != 3:
        raise SystemExit(__doc__)
    spec = json.loads(Path(sys.argv[1]).read_text(encoding="utf-8"))
    out = Path(sys.argv[2])

    font_path = spec["font"]
    sizes = spec["sizes"]
    icons = spec["icons"]
    prefix = spec.get("prefix", "ngl_icon")

    parts = [
        "/*\n * GENERATED by tools/genicons/genicons.py - do not edit.\n"
        f" * Source face: {Path(font_path).name}\n"
        f" * Sizes: {', '.join(str(s) for s in sizes)}\n */\n",
        '#include "ngl.h"\n',
    ]
    total = 0

    for name, cp_text in icons.items():
        codepoint = int(cp_text, 0)
        for cell in sizes:
            pt, data = render(font_path, codepoint, cell)
            sym = f"{prefix}_{name}_{cell}"
            total += len(data)

            # A codepoint the font does not have renders as nothing at all, and
            # would otherwise ship as a silently invisible icon.
            if not any(data):
                raise SystemExit(f"{name}: U+{codepoint:04X} is blank in "
                                 f"{Path(font_path).name} - wrong codepoint?")

            parts.append(f"\n/* {name} U+{codepoint:04X} at {cell}px "
                         f"(rasterised {pt}pt) */")
            parts.append(f"\nstatic const uint8_t {sym}_a[] = {{")
            for row in range(cell):
                chunk = data[row * cell:(row + 1) * cell]
                parts.append("\n    " + " ".join(f"0x{b:02X}," for b in chunk))
            parts.append("\n};\n")
            parts.append(f"""
const ngl_icon_t {sym} = {{
    .alpha = {sym}_a,
    .w     = {cell},
    .h     = {cell},
    .name  = "{name}",
}};
""")
            print(f"  {sym}: {len(data)} bytes")

    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("".join(parts), encoding="utf-8")

    # Companion header, so callers get declarations without hand-maintaining
    # them. Goes to include/ when the source lands in a component's src/.
    hdr = (out.parent.parent / "include" / (out.stem + ".h")
           if out.parent.name == "src" else out.with_suffix(".h"))
    decl = ["/* GENERATED by tools/genicons/genicons.py - do not edit. */\n",
            "#pragma once\n", '#include "ngl.h"\n\n']
    for name in icons:
        for cell in sizes:
            decl.append(f"extern const ngl_icon_t {prefix}_{name}_{cell};\n")
    hdr.write_text("".join(decl), encoding="utf-8")

    print(f"wrote {out} and {hdr.name} ({total} bytes of bitmap)")


main()
