"""
Generate 1-bit bitmap font tables for the ngl graphics library.

Rasterises a TTF into fixed cells and emits src/ngl_font_data.c. Rerun this to
change font or sizes; the output is generated, do not hand-edit it.

    python tools/genfont/genfont.py C:/Windows/Fonts/CascadiaCode.ttf \n           neos/components/ngl/src/ngl_font_data.c
"""
import sys
from PIL import Image, ImageDraw, ImageFont

FIRST, LAST = 32, 126
# Semantic names, not dimensions: sizes get retuned, and these are ABI
# symbols that apps link against by name.
CELLS = [("ngl_font_small", 16, 32), ("ngl_font_large", 24, 48)]


def best_size(path, cw, ch):
    """Largest point size whose advance fits cw and whose ascent+descent fits ch."""
    best = None
    for size in range(4, 80):
        f = ImageFont.truetype(path, size)
        adv = f.getlength("M")
        asc, desc = f.getmetrics()
        if adv <= cw and (asc + desc) <= ch:
            best = (size, f, asc, desc)
    if best is None:
        raise SystemExit(f"no size fits {cw}x{ch}")
    return best


def render(path, cw, ch):
    size, font, asc, desc = best_size(path, cw, ch)
    y0 = (ch - (asc + desc)) // 2
    bpr = (cw + 7) // 8
    rows = []
    for code in range(FIRST, LAST + 1):
        img = Image.new("L", (cw, ch), 0)
        ImageDraw.Draw(img).text((0, y0), chr(code), fill=255, font=font)
        px = img.load()
        glyph = []
        for y in range(ch):
            for b in range(bpr):
                byte = 0
                for bit in range(8):
                    x = b * 8 + bit
                    if x < cw and px[x, y] >= 128:
                        byte |= 0x80 >> bit
                glyph.append(byte)
        rows.append(glyph)
    return size, bpr, rows


def main():
    ttf, out = sys.argv[1], sys.argv[2]
    parts = [
        "/*\n * GENERATED by tools/genfont.py - do not edit.\n"
        f" * Source face: {ttf.split('/')[-1]}\n */\n",
        '#include "ngl.h"\n',
    ]
    for name, cw, ch in CELLS:
        size, bpr, rows = render(ttf, cw, ch)
        parts.append(f"\n/* {name}: {cw}x{ch} cells, rasterised at {size}pt */")
        parts.append(f"\nstatic const uint8_t {name}_bits[] = {{")
        for code, glyph in zip(range(FIRST, LAST + 1), rows):
            ch_repr = chr(code) if code != 92 else "backslash"
            parts.append(f"\n    /* '{ch_repr}' */ " +
                         " ".join(f"0x{b:02X}," for b in glyph))
        parts.append("\n};\n")
        parts.append(f"""
const ngl_font_t {name} = {{
    .bits         = {name}_bits,
    .width        = {cw},
    .height       = {ch},
    .bytes_per_row= {bpr},
    .first        = {FIRST},
    .last         = {LAST},
}};
""")
        print(f"{name}: {cw}x{ch} @ {size}pt, {len(rows) * ch * bpr} bytes")
    open(out, "w", encoding="utf-8").write("".join(parts))
    print("wrote", out)


main()
