# Bump the NeOS build number and regenerate the header the system bar reads.
#
# Run as a script (cmake -P) from a build-time custom target, so it fires on
# every build rather than only when CMake reconfigures - the whole point of the
# number is to tell two images apart when nothing else about them differs.
#
#   COUNTER  the tracked file holding the current number
#   HEADER   the generated header to write
#
# The counter is a plain integer in its own file rather than something derived
# from git, because the tablet is usually flashed with work that is not
# committed yet - and a version that only moves on commit would name the wrong
# image exactly when it matters.

if(NOT COUNTER OR NOT HEADER)
    message(FATAL_ERROR "bump_build: COUNTER and HEADER are both required")
endif()

set(n 0)
if(EXISTS "${COUNTER}")
    file(READ "${COUNTER}" raw)
    string(REGEX MATCH "[0-9]+" n "${raw}")
    if(NOT n)
        set(n 0)
    endif()
endif()
math(EXPR n "${n} + 1")

file(WRITE "${COUNTER}" "${n}\n")

# Written unconditionally: the rewrite is what makes the one file that shows
# the number recompile, and that is a single object plus a relink.
get_filename_component(header_dir "${HEADER}" DIRECTORY)
file(MAKE_DIRECTORY "${header_dir}")
file(WRITE "${HEADER}"
"/* Generated by neos/cmake/bump_build.cmake - do not edit, do not commit. */
#pragma once

#define NEOS_BUILD ${n}
")
