/*
 * ngl icons: 8-bit alpha bitmaps, tinted at draw time.
 *
 * One bitmap serves every colour the theme needs, and the coverage values give
 * smooth edges that a 1-bit glyph could not. Generated by tools/genicons.
 */
#include <string.h>

#include "ngl.h"
#include "ngl_icon_data.h"
#include "ngl_internal.h"

void ngl_icon(ngl_surface_t *s, int16_t x, int16_t y, const ngl_icon_t *ic, ngl_color_t c)
{
    if (!s || !ic || !ic->alpha) {
        return;
    }
    for (int16_t j = 0; j < (int16_t)ic->h; j++) {
        const uint8_t *row = &ic->alpha[(size_t)j * ic->w];
        for (int16_t i = 0; i < (int16_t)ic->w; i++) {
            if (row[i]) {
                ngl_pixel_blend(s, (int16_t)(x + i), (int16_t)(y + j), c, row[i]);
            }
        }
    }
    if (s == ngl_screen()) {
        const ngl_rect_t r = ngl_rect(x, y, (int16_t)ic->w, (int16_t)ic->h);
        ngl_dirty(&r);
    }
}

/* ------------------------------------------------------------------ */
/* Lookup                                                              */
/* ------------------------------------------------------------------ */

/*
 * Apps reach icons through this, not by linking the objects themselves.
 *
 * ngl_icon_data.c is generated from tools/genicons/icons.json, so exporting
 * the individual ngl_icon_* objects across the syscall table would make that
 * JSON file part of the ABI - adding or renaming an icon would become a
 * version event, and dropping one would break apps already on a card. One
 * lookup keeps the icon set free to change and costs apps a strcmp they do
 * once at startup.
 *
 * Adding an icon means adding it to icons.json, regenerating, and adding the
 * two rows below. Nothing outside ngl has to know.
 */
static const ngl_icon_t *const s_icons[] = {
    &ngl_icon_smile_24,
    &ngl_icon_smile_32,
    &ngl_icon_dizzy_24,
    &ngl_icon_dizzy_32,
    &ngl_icon_bomb_24,
    &ngl_icon_bomb_32,
    &ngl_icon_close_24,
    &ngl_icon_close_32,
    &ngl_icon_battery_24,
    &ngl_icon_battery_32,
    &ngl_icon_wifi_24,
    &ngl_icon_wifi_32,
    &ngl_icon_settings_24,
    &ngl_icon_settings_32,
    &ngl_icon_clock_24,
    &ngl_icon_clock_32,
    &ngl_icon_folder_24,
    &ngl_icon_folder_32,
    &ngl_icon_home_24,
    &ngl_icon_home_32,
    &ngl_icon_back_24,
    &ngl_icon_back_32,
};

const ngl_icon_t *ngl_icon_find(const char *name, int16_t px)
{
    if (!name) {
        return NULL;
    }
    for (size_t i = 0; i < sizeof(s_icons) / sizeof(s_icons[0]); i++) {
        const ngl_icon_t *ic = s_icons[i];
        if (ic->w == (uint16_t)px && strcmp(ic->name, name) == 0) {
            return ic;
        }
    }
    return NULL;
}
