/*
 * ngl - NeOS Graphic Library
 *
 * A small, framebuffer-based 2D library owned by the launcher and exported to
 * loaded ELF apps through the syscall table. Deliberately not LVGL: every
 * symbol here is one the OS commits to, so the API is kept small enough to
 * read in one sitting and version honestly.
 *
 * Coordinates are pixels, origin top-left. Colour is RGB565 throughout, which
 * is what the Tab5 panel consumes - no conversion on the hot path.
 *
 * Drawing goes into a surface. ngl_screen() is the surface backed by the
 * panel's framebuffer; call ngl_flush() when a frame is done, which pushes the
 * dirty region to the display. Every draw call marks its own bounds dirty, so
 * an app that draws a 40x40 button repaints 40 rows, not 1280.
 */
#pragma once

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ------------------------------------------------------------------ */
/* Types                                                               */
/* ------------------------------------------------------------------ */

typedef uint16_t ngl_color_t;

/** Pack 8-bit RGB into RGB565. */
#define NGL_RGB(r, g, b) \
    ((ngl_color_t)((((r) & 0xF8) << 8) | (((g) & 0xFC) << 3) | ((b) >> 3)))

#define NGL_BLACK   NGL_RGB(0, 0, 0)
#define NGL_WHITE   NGL_RGB(255, 255, 255)
#define NGL_RED     NGL_RGB(220, 40, 40)
#define NGL_GREEN   NGL_RGB(0, 200, 80)
#define NGL_BLUE    NGL_RGB(50, 120, 240)
#define NGL_YELLOW  NGL_RGB(230, 180, 0)
#define NGL_GREY    NGL_RGB(128, 128, 128)

typedef struct {
    int16_t x, y, w, h;
} ngl_rect_t;

/** Rotation applied between the app's coordinates and the physical panel. */
typedef enum {
    NGL_ROT_0   = 0,   /**< native portrait, 720x1280 */
    NGL_ROT_90  = 1,
    NGL_ROT_180 = 2,
    NGL_ROT_270 = 3,
} ngl_rotation_t;

/**
 * A drawable pixel buffer.
 *
 * Opaque outside ngl, on purpose. Every other type in this header is frozen
 * for the life of the major ABI because apps compile its layout in; a surface
 * is the one thing the launcher is likely to want to grow - a scale factor, a
 * second clip, an alpha plane - so apps are given a handle and accessors
 * instead, and growing it stays a minor bump. Apps get one from ngl_screen(),
 * ngl_surface_new() or ngl_surface_wrap().
 */
typedef struct ngl_surface ngl_surface_t;

#ifdef NGL_INTERNAL
/*
 * The layout, visible only to ngl's own sources - the component compiles with
 * -DNGL_INTERNAL, and nothing propagates it to dependents. If you find
 * yourself wanting this in main/ or in an app, add an accessor instead.
 *
 * `stride` is in pixels, not bytes, and may exceed `w` for sub-surfaces.
 * `clip` bounds every draw call; it starts as the full surface.
 */
struct ngl_surface {
    ngl_color_t *px;
    int16_t     w, h;
    int16_t     stride;
    ngl_rect_t   clip;
    bool        owns_px;
};
#endif

/** 1-bit bitmap font, rows packed MSB-first. See tools/genfont.py. */
typedef struct {
    const uint8_t *bits;
    uint8_t        width, height;
    uint8_t        bytes_per_row;
    uint8_t        first, last;
} ngl_font_t;

/**
 * 8-bit alpha icon, tinted when drawn. Generated by tools/genicons.
 *
 * Alpha rather than 1-bit: icons are large enough for jagged edges to show,
 * and one bitmap can then serve every colour the theme needs.
 */
typedef struct {
    const uint8_t *alpha;      /**< w*h coverage values */
    uint16_t       w, h;
    const char    *name;
} ngl_icon_t;

/* Semantic names, not dimensions: the sizes get retuned, these symbols do
   not - apps link against them by name through the syscall table. */
extern const ngl_font_t ngl_font_small;   /* 16x32 */
extern const ngl_font_t ngl_font_large;   /* 24x48 */

/*
 * Frozen layouts.
 *
 * These three cross into apps by value or get their fields read there - a rect
 * is passed and returned whole, and apps centre things on ngl_font_small.height
 * and ic->w - so their sizes and offsets are compiled into every app on the
 * card. Changing one is a NEOS_ABI_MAJOR bump, not a minor, and this is where
 * you find that out rather than in a garbled frame on the panel. Adding a
 * field to the end of a font or an icon shifts nothing and is still a minor.
 */
_Static_assert(sizeof(ngl_color_t) == 2, "ngl_color_t is RGB565; widening it is an ABI major");
_Static_assert(sizeof(ngl_rect_t) == 8, "ngl_rect_t is passed by value; its layout is ABI");
_Static_assert(offsetof(ngl_rect_t, x) == 0, "ngl_rect_t layout is frozen for ABI v1");
_Static_assert(offsetof(ngl_rect_t, y) == 2, "ngl_rect_t layout is frozen for ABI v1");
_Static_assert(offsetof(ngl_rect_t, w) == 4, "ngl_rect_t layout is frozen for ABI v1");
_Static_assert(offsetof(ngl_rect_t, h) == 6, "ngl_rect_t layout is frozen for ABI v1");
_Static_assert(offsetof(ngl_font_t, bits)          == 0, "ngl_font_t layout is frozen for ABI v1");
_Static_assert(offsetof(ngl_font_t, width)         == 4, "ngl_font_t layout is frozen for ABI v1");
_Static_assert(offsetof(ngl_font_t, height)        == 5, "ngl_font_t layout is frozen for ABI v1");
_Static_assert(offsetof(ngl_font_t, bytes_per_row) == 6, "ngl_font_t layout is frozen for ABI v1");
_Static_assert(offsetof(ngl_font_t, first)         == 7, "ngl_font_t layout is frozen for ABI v1");
_Static_assert(offsetof(ngl_font_t, last)          == 8, "ngl_font_t layout is frozen for ABI v1");
_Static_assert(offsetof(ngl_icon_t, alpha) == 0, "ngl_icon_t layout is frozen for ABI v1");
_Static_assert(offsetof(ngl_icon_t, w)     == 4, "ngl_icon_t layout is frozen for ABI v1");
_Static_assert(offsetof(ngl_icon_t, h)     == 6, "ngl_icon_t layout is frozen for ABI v1");
_Static_assert(offsetof(ngl_icon_t, name)  == 8, "ngl_icon_t layout is frozen for ABI v1");

/* Apps switch on these, so the numbers are ABI. Appending is a minor bump;
   renumbering NGL_ROT_90 out from under a built app is not. */
_Static_assert(NGL_ROT_0 == 0 && NGL_ROT_90 == 1 && NGL_ROT_180 == 2 && NGL_ROT_270 == 3,
               "ngl_rotation_t values are frozen for ABI v1");

/* ------------------------------------------------------------------ */
/* Rectangles                                                          */
/* ------------------------------------------------------------------ */

static inline ngl_rect_t ngl_rect(int16_t x, int16_t y, int16_t w, int16_t h)
{
    ngl_rect_t r = { x, y, w, h };
    return r;
}

bool ngl_rect_intersect(const ngl_rect_t *a, const ngl_rect_t *b, ngl_rect_t *out);
ngl_rect_t ngl_rect_union(const ngl_rect_t *a, const ngl_rect_t *b);
bool ngl_rect_contains(const ngl_rect_t *r, int16_t x, int16_t y);
static inline bool ngl_rect_empty(const ngl_rect_t *r) { return r->w <= 0 || r->h <= 0; }

/* ------------------------------------------------------------------ */
/* Screen: the panel-backed surface                                    */
/* ------------------------------------------------------------------ */

/**
 * Bind ngl to an initialised esp_lcd panel.
 *
 * @param panel  esp_lcd_panel_handle_t (void* to keep esp_lcd out of this header)
 * @param w,h    panel resolution in pixels
 * @return 0 on success, negative on failure
 */
int ngl_screen_init(void *panel, int16_t w, int16_t h);

/** The panel-backed surface. NULL before ngl_screen_init(). */
ngl_surface_t *ngl_screen(void);

/** Mark a region as needing to reach the panel. Draw calls do this for you. */
void ngl_dirty(const ngl_rect_t *r);

/** Mark the whole screen dirty. */
void ngl_dirty_all(void);

/** Push the accumulated dirty region to the panel and reset it. */
void ngl_flush(void);

/* ------------------------------------------------------------------ */
/* Rotation                                                            */
/* ------------------------------------------------------------------ */

/**
 * Rotate the display.
 *
 * Apps keep drawing in logical coordinates - after a 90 degree rotation
 * ngl_screen() really is 1280x720 - and ngl maps to the panel on flush. Changing
 * rotation reallocates the back buffer and marks everything dirty, so the
 * caller must repaint.
 */
void ngl_set_rotation(ngl_rotation_t r);

/**
 * Map a point from panel coordinates to screen coordinates.
 *
 * The touch controller reports in the panel native frame, which does not
 * move when the screen rotates. Everything an app draws is in the rotated
 * frame, so a touch has to come back through this before it can be compared
 * against anything on screen.
 */
void ngl_from_panel(int16_t px, int16_t py, int16_t *lx, int16_t *ly);
ngl_rotation_t ngl_rotation(void);

/* ------------------------------------------------------------------ */
/* System bar                                                          */
/* ------------------------------------------------------------------ */

/** Paints the reserved bar. Called by ngl; the OS supplies it. */
typedef void (*ngl_bar_painter_t)(ngl_surface_t *s, ngl_rect_t bar);

/**
 * Reserve `h` pixels along the top of the logical screen for the system bar.
 *
 * The reservation is enforced, not advisory: the screen surface's clip
 * excludes the bar and ngl_clip_set() cannot widen past it, so a loaded app
 * cannot draw over the close button no matter what it asks for. Only
 * ngl_clear() repaints it, through `painter`.
 */
void ngl_reserve_top(int16_t h, ngl_bar_painter_t painter);

int16_t   ngl_bar_height(void);
ngl_rect_t ngl_bar_rect(void);

/** The area apps may actually draw in: the screen minus the system bar. */
ngl_rect_t ngl_app_area(void);

/** Repaint the bar. ngl_clear() does this for you. */
void ngl_bar_paint(void);

/**
 * Draw directly into one region of the system bar.
 *
 * Lifts the bar reservation and clips to `region` (screen coordinates), so a
 * bar widget can repaint just itself instead of forcing a whole-bar repaint -
 * which matters for anything animating. Returns NULL if there is no bar.
 *
 * Holds the screen lock until ngl_bar_end(), so this must always be paired and
 * kept short. Not exported to apps: the bar belongs to the OS.
 */
ngl_surface_t *ngl_bar_begin(ngl_rect_t region);
void ngl_bar_end(void);

/* ------------------------------------------------------------------ */
/* Surfaces                                                            */
/* ------------------------------------------------------------------ */

/** Allocate an off-screen surface in PSRAM. Free with ngl_surface_free(). */
ngl_surface_t *ngl_surface_new(int16_t w, int16_t h);

/**
 * Wrap caller-owned pixels. Free with ngl_surface_free(), which frees the
 * handle but leaves `px` alone - those stay the caller's.
 *
 * Returns a handle rather than filling one in: a surface is opaque to apps, so
 * they have nowhere to put it. `stride` is in pixels; 0 means `w`.
 */
ngl_surface_t *ngl_surface_wrap(ngl_color_t *px, int16_t w, int16_t h, int16_t stride);

void ngl_surface_free(ngl_surface_t *s);

/** Restrict drawing to `r` (intersected with the surface). NULL resets. */
void ngl_clip_set(ngl_surface_t *s, const ngl_rect_t *r);

/* Everything callers used to read straight out of the struct. */
int16_t ngl_surface_w(const ngl_surface_t *s);
int16_t ngl_surface_h(const ngl_surface_t *s);

/** The whole surface as a rect: {0, 0, w, h}. */
ngl_rect_t ngl_surface_bounds(const ngl_surface_t *s);

/** What draws are currently confined to, in surface coordinates. */
ngl_rect_t ngl_surface_clip(const ngl_surface_t *s);

/* ------------------------------------------------------------------ */
/* Primitives                                                          */
/* ------------------------------------------------------------------ */

void ngl_clear(ngl_surface_t *s, ngl_color_t c);
void ngl_pixel(ngl_surface_t *s, int16_t x, int16_t y, ngl_color_t c);

/** Blend `c` over the pixel at (x,y). a: 0 = keep, 255 = replace. */
void ngl_pixel_blend(ngl_surface_t *s, int16_t x, int16_t y, ngl_color_t c, uint8_t a);

void ngl_fill_rect(ngl_surface_t *s, ngl_rect_t r, ngl_color_t c);
void ngl_draw_rect(ngl_surface_t *s, ngl_rect_t r, ngl_color_t c, int16_t thickness);

void ngl_fill_round_rect(ngl_surface_t *s, ngl_rect_t r, int16_t radius, ngl_color_t c);
void ngl_draw_round_rect(ngl_surface_t *s, ngl_rect_t r, int16_t radius, ngl_color_t c,
                        int16_t thickness);

void ngl_hline(ngl_surface_t *s, int16_t x, int16_t y, int16_t w, ngl_color_t c);
void ngl_vline(ngl_surface_t *s, int16_t x, int16_t y, int16_t h, ngl_color_t c);

/** Hard-edged line (Bresenham). Cheap; use for axis-ish lines and borders. */
void ngl_line(ngl_surface_t *s, int16_t x0, int16_t y0, int16_t x1, int16_t y1, ngl_color_t c);

/** Anti-aliased line (Xiaolin Wu). */
void ngl_line_aa(ngl_surface_t *s, int16_t x0, int16_t y0, int16_t x1, int16_t y1, ngl_color_t c);

/* ------------------------------------------------------------------ */
/* Blitting                                                            */
/* ------------------------------------------------------------------ */

/** Copy `src_rect` of `src` (NULL = all of it) to (x,y) in `dst`. */
void ngl_blit(ngl_surface_t *dst, int16_t x, int16_t y,
             const ngl_surface_t *src, const ngl_rect_t *src_rect);

/** As ngl_blit(), but pixels equal to `key` are left untouched. */
void ngl_blit_key(ngl_surface_t *dst, int16_t x, int16_t y,
                 const ngl_surface_t *src, const ngl_rect_t *src_rect, ngl_color_t key);

/* ------------------------------------------------------------------ */
/* Text                                                                */
/* ------------------------------------------------------------------ */

/** Draw `str` with its top-left at (x,y). Returns the x after the last glyph. */
int16_t ngl_text(ngl_surface_t *s, int16_t x, int16_t y, const char *str,
                const ngl_font_t *f, ngl_color_t c);

/** As ngl_text(), but fills the glyph cells with `bg` first. */
int16_t ngl_text_bg(ngl_surface_t *s, int16_t x, int16_t y, const char *str,
                   const ngl_font_t *f, ngl_color_t c, ngl_color_t bg);

int16_t ngl_text_width(const ngl_font_t *f, const char *str);

/* ------------------------------------------------------------------ */
/* Icons                                                               */
/* ------------------------------------------------------------------ */

/** Draw `ic` at (x,y), tinted `c`, blended by its alpha. */
void ngl_icon(ngl_surface_t *s, int16_t x, int16_t y, const ngl_icon_t *ic, ngl_color_t c);

/**
 * Find an icon by name and pixel size, e.g. ngl_icon_find("bomb", 32).
 *
 * This is how apps get at icons: the individual objects are generated from
 * icons.json and are deliberately not part of the ABI, so that the icon set
 * can change without breaking apps already on a card. NULL if there is no
 * such icon at that size - draw nothing rather than guessing a substitute.
 */
const ngl_icon_t *ngl_icon_find(const char *name, int16_t px);

#ifdef __cplusplus
}
#endif
