/*
 * ngl - NeOS Graphic Library
 *
 * A small, framebuffer-based 2D library owned by the launcher and exported to
 * loaded ELF apps through the syscall table. Deliberately not LVGL: every
 * symbol here is one the OS commits to, so the API is kept small enough to
 * read in one sitting and version honestly.
 *
 * Coordinates are pixels, origin top-left. Colour is RGB565 throughout, which
 * is what the Tab5 panel consumes - no conversion on the hot path.
 *
 * Drawing goes into a surface. ngl_screen() is the surface backed by the
 * panel's framebuffer; call ngl_flush() when a frame is done, which pushes the
 * dirty region to the display. Every draw call marks its own bounds dirty, so
 * an app that draws a 40x40 button repaints 40 rows, not 1280.
 */
#pragma once

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ------------------------------------------------------------------ */
/* Types                                                               */
/* ------------------------------------------------------------------ */

typedef uint16_t ngl_color_t;

/** Pack 8-bit RGB into RGB565. */
#define NGL_RGB(r, g, b) \
    ((ngl_color_t)((((r) & 0xF8) << 8) | (((g) & 0xFC) << 3) | ((b) >> 3)))

#define NGL_BLACK   NGL_RGB(0, 0, 0)
#define NGL_WHITE   NGL_RGB(255, 255, 255)
#define NGL_RED     NGL_RGB(220, 40, 40)
#define NGL_GREEN   NGL_RGB(0, 200, 80)
#define NGL_BLUE    NGL_RGB(50, 120, 240)
#define NGL_YELLOW  NGL_RGB(230, 180, 0)
#define NGL_GREY    NGL_RGB(128, 128, 128)

typedef struct {
    int16_t x, y, w, h;
} ngl_rect_t;

/** Rotation applied between the app's coordinates and the physical panel. */
typedef enum {
    NGL_ROT_0   = 0,   /**< native portrait, 720x1280 */
    NGL_ROT_90  = 1,
    NGL_ROT_180 = 2,
    NGL_ROT_270 = 3,
} ngl_rotation_t;

/**
 * A drawable pixel buffer.
 *
 * Opaque outside ngl, on purpose. Every other type in this header is frozen
 * for the life of the major ABI because apps compile its layout in; a surface
 * is the one thing the launcher is likely to want to grow - a scale factor, a
 * second clip, an alpha plane - so apps are given a handle and accessors
 * instead, and growing it stays a minor bump. Apps get one from ngl_screen(),
 * ngl_surface_new() or ngl_surface_wrap().
 */
typedef struct ngl_surface ngl_surface_t;

#ifdef NGL_INTERNAL
/*
 * The layout, visible only to ngl's own sources - the component compiles with
 * -DNGL_INTERNAL, and nothing propagates it to dependents. If you find
 * yourself wanting this in main/ or in an app, add an accessor instead.
 *
 * `stride` is in pixels, not bytes, and may exceed `w` for sub-surfaces.
 * `clip` bounds every draw call; it starts as the full surface.
 */
struct ngl_surface {
    ngl_color_t *px;
    int16_t     w, h;
    int16_t     stride;
    ngl_rect_t   clip;
    bool        owns_px;
};
#endif

/** 1-bit bitmap font, rows packed MSB-first. See tools/genfont.py. */
typedef struct {
    const uint8_t *bits;
    uint8_t        width, height;
    uint8_t        bytes_per_row;
    uint8_t        first, last;
} ngl_font_t;

/**
 * 8-bit alpha icon, tinted when drawn. Generated by tools/genicons.
 *
 * Alpha rather than 1-bit: icons are large enough for jagged edges to show,
 * and one bitmap can then serve every colour the theme needs.
 */
typedef struct {
    const uint8_t *alpha;      /**< w*h coverage values */
    uint16_t       w, h;
    const char    *name;
} ngl_icon_t;

/* Semantic names, not dimensions: the sizes get retuned, these symbols do
   not - apps link against them by name through the syscall table. */
extern const ngl_font_t ngl_font_small;   /* 16x32 */
extern const ngl_font_t ngl_font_large;   /* 24x48 */

/*
 * Frozen layouts.
 *
 * These three cross into apps by value or get their fields read there - a rect
 * is passed and returned whole, and apps centre things on ngl_font_small.height
 * and ic->w - so their sizes and offsets are compiled into every app on the
 * card. Changing one is a NEOS_ABI_MAJOR bump, not a minor, and this is where
 * you find that out rather than in a garbled frame on the panel. Adding a
 * field to the end of a font or an icon shifts nothing and is still a minor.
 */
_Static_assert(sizeof(ngl_color_t) == 2, "ngl_color_t is RGB565; widening it is an ABI major");
_Static_assert(sizeof(ngl_rect_t) == 8, "ngl_rect_t is passed by value; its layout is ABI");
_Static_assert(offsetof(ngl_rect_t, x) == 0, "ngl_rect_t layout is frozen for ABI v1");
_Static_assert(offsetof(ngl_rect_t, y) == 2, "ngl_rect_t layout is frozen for ABI v1");
_Static_assert(offsetof(ngl_rect_t, w) == 4, "ngl_rect_t layout is frozen for ABI v1");
_Static_assert(offsetof(ngl_rect_t, h) == 6, "ngl_rect_t layout is frozen for ABI v1");
_Static_assert(offsetof(ngl_font_t, bits)          == 0, "ngl_font_t layout is frozen for ABI v1");
_Static_assert(offsetof(ngl_font_t, width)         == 4, "ngl_font_t layout is frozen for ABI v1");
_Static_assert(offsetof(ngl_font_t, height)        == 5, "ngl_font_t layout is frozen for ABI v1");
_Static_assert(offsetof(ngl_font_t, bytes_per_row) == 6, "ngl_font_t layout is frozen for ABI v1");
_Static_assert(offsetof(ngl_font_t, first)         == 7, "ngl_font_t layout is frozen for ABI v1");
_Static_assert(offsetof(ngl_font_t, last)          == 8, "ngl_font_t layout is frozen for ABI v1");
_Static_assert(offsetof(ngl_icon_t, alpha) == 0, "ngl_icon_t layout is frozen for ABI v1");
_Static_assert(offsetof(ngl_icon_t, w)     == 4, "ngl_icon_t layout is frozen for ABI v1");
_Static_assert(offsetof(ngl_icon_t, h)     == 6, "ngl_icon_t layout is frozen for ABI v1");
_Static_assert(offsetof(ngl_icon_t, name)  == 8, "ngl_icon_t layout is frozen for ABI v1");

/* Apps switch on these, so the numbers are ABI. Appending is a minor bump;
   renumbering NGL_ROT_90 out from under a built app is not. */
_Static_assert(NGL_ROT_0 == 0 && NGL_ROT_90 == 1 && NGL_ROT_180 == 2 && NGL_ROT_270 == 3,
               "ngl_rotation_t values are frozen for ABI v1");

/* ------------------------------------------------------------------ */
/* Rectangles                                                          */
/* ------------------------------------------------------------------ */

static inline ngl_rect_t ngl_rect(int16_t x, int16_t y, int16_t w, int16_t h)
{
    ngl_rect_t r = { x, y, w, h };
    return r;
}

bool ngl_rect_intersect(const ngl_rect_t *a, const ngl_rect_t *b, ngl_rect_t *out);
ngl_rect_t ngl_rect_union(const ngl_rect_t *a, const ngl_rect_t *b);
bool ngl_rect_contains(const ngl_rect_t *r, int16_t x, int16_t y);
static inline bool ngl_rect_empty(const ngl_rect_t *r) { return r->w <= 0 || r->h <= 0; }

/* ------------------------------------------------------------------ */
/* Screen: the panel-backed surface                                    */
/* ------------------------------------------------------------------ */

/**
 * Bind ngl to an initialised esp_lcd panel.
 *
 * @param panel  esp_lcd_panel_handle_t (void* to keep esp_lcd out of this header)
 * @param w,h    panel resolution in pixels
 * @return 0 on success, negative on failure
 */
int ngl_screen_init(void *panel, int16_t w, int16_t h);

/** The panel-backed surface. NULL before ngl_screen_init(). */
ngl_surface_t *ngl_screen(void);

/** Mark a region as needing to reach the panel. Draw calls do this for you. */
void ngl_dirty(const ngl_rect_t *r);

/** Mark the whole screen dirty. */
void ngl_dirty_all(void);

/** Push the accumulated dirty region to the panel and reset it. */
void ngl_flush(void);

/* ------------------------------------------------------------------ */
/* Rotation                                                            */
/* ------------------------------------------------------------------ */

/**
 * Rotate the display.
 *
 * Apps keep drawing in logical coordinates - after a 90 degree rotation
 * ngl_screen() really is 1280x720 - and ngl maps to the panel on flush. Changing
 * rotation reallocates the back buffer and marks everything dirty, so the
 * caller must repaint.
 */
void ngl_set_rotation(ngl_rotation_t r);

/**
 * Map a point from panel coordinates to screen coordinates.
 *
 * The touch controller reports in the panel native frame, which does not
 * move when the screen rotates. Everything an app draws is in the rotated
 * frame, so a touch has to come back through this before it can be compared
 * against anything on screen.
 */
void ngl_from_panel(int16_t px, int16_t py, int16_t *lx, int16_t *ly);
ngl_rotation_t ngl_rotation(void);

/* ------------------------------------------------------------------ */
/* System bar                                                          */
/* ------------------------------------------------------------------ */

/** Paints the reserved bar. Called by ngl; the OS supplies it. */
typedef void (*ngl_bar_painter_t)(ngl_surface_t *s, ngl_rect_t bar);

/**
 * Reserve `h` pixels along the top of the logical screen for the system bar.
 *
 * The reservation is enforced, not advisory: the screen surface's clip
 * excludes the bar and ngl_clip_set() cannot widen past it, so a loaded app
 * cannot draw over the close button no matter what it asks for. Only
 * ngl_clear() repaints it, through `painter`.
 */
void ngl_reserve_top(int16_t h, ngl_bar_painter_t painter);

int16_t   ngl_bar_height(void);
ngl_rect_t ngl_bar_rect(void);

/** The area apps may actually draw in: the screen minus the system bar. */
ngl_rect_t ngl_app_area(void);

/** Repaint the bar. ngl_clear() does this for you. */
void ngl_bar_paint(void);

/**
 * Draw directly into one region of the system bar.
 *
 * Lifts the bar reservation and clips to `region` (screen coordinates), so a
 * bar widget can repaint just itself instead of forcing a whole-bar repaint -
 * which matters for anything animating. Returns NULL if there is no bar.
 *
 * Holds the screen lock until ngl_bar_end(), so this must always be paired and
 * kept short. Not exported to apps: the bar belongs to the OS.
 */
ngl_surface_t *ngl_bar_begin(ngl_rect_t region);
void ngl_bar_end(void);

/* ------------------------------------------------------------------ */
/* Modal overlays                                                      */
/* ------------------------------------------------------------------ */

/*
 * A panel the OS puts over the running app - the keyboard, the Wi-Fi picker,
 * the clock page.
 *
 * NeOS cannot pause an app: it is ordinary code running on the boot task's
 * stack, and there is no scheduler entry to suspend. So a modal panel takes
 * the screen instead of the CPU. Between enter and leave, every draw call
 * from any task other than the one that entered is dropped at the point where
 * it would touch a pixel - ngl_clear() included, which is the one call that
 * otherwise bypasses the clip. The app keeps running and keeps computing
 * frames; none of them arrive.
 *
 * The pixels underneath are saved on enter and put back on leave, so the app
 * comes back to exactly the screen it had. It is never told any of this
 * happened, which is the point: an app written before there was a keyboard
 * still works underneath one.
 *
 * Not exported to apps. An app that could take the screen from the OS could
 * take it from the close button too.
 */

/**
 * Take the screen.
 *
 * Nests, because panels do - the Wi-Fi list raises the keyboard over itself to
 * take a password, and has to get its own list back and not the app's. Only
 * the task that took the screen may take it again; anyone else gets false,
 * which is what stops two panels existing at once.
 */
bool ngl_overlay_enter(void);

/** Give it back, restoring whatever this level found underneath it. */
void ngl_overlay_leave(void);

/**
 * Put back what this level found, without giving the screen up.
 *
 * For a panel that has to redraw itself from scratch - it moved, or the app
 * area under it changed size. Without this a panel would be compositing onto
 * its own last frame, and anything it draws by blending, a dimmed backdrop
 * most of all, would get darker every time it repainted.
 */
void ngl_overlay_restore(void);

/** True while a panel owns the screen. */
bool ngl_overlay_active(void);

/**
 * Draw into one region of the overlay, in screen coordinates.
 *
 * The same shape as ngl_bar_begin(), and for the same reason: it holds the
 * screen lock until ngl_overlay_end(), so it must be paired and kept short.
 * Returns NULL unless the calling task is the one that entered.
 */
ngl_surface_t *ngl_overlay_begin(ngl_rect_t region);
void ngl_overlay_end(void);

/**
 * Darken a region in place, `amount` 0-255.
 *
 * What makes a panel read as being in front of something rather than instead
 * of it. Done as a blend against black rather than a translucent fill so that
 * whatever is underneath still shows through at full detail.
 */
void ngl_dim_rect(ngl_surface_t *s, ngl_rect_t r, uint8_t amount);

/* ------------------------------------------------------------------ */
/* Surfaces                                                            */
/* ------------------------------------------------------------------ */

/** Allocate an off-screen surface in PSRAM. Free with ngl_surface_free(). */
ngl_surface_t *ngl_surface_new(int16_t w, int16_t h);

/**
 * Wrap caller-owned pixels. Free with ngl_surface_free(), which frees the
 * handle but leaves `px` alone - those stay the caller's.
 *
 * Returns a handle rather than filling one in: a surface is opaque to apps, so
 * they have nowhere to put it. `stride` is in pixels; 0 means `w`.
 */
ngl_surface_t *ngl_surface_wrap(ngl_color_t *px, int16_t w, int16_t h, int16_t stride);

void ngl_surface_free(ngl_surface_t *s);

/** Restrict drawing to `r` (intersected with the surface). NULL resets. */
void ngl_clip_set(ngl_surface_t *s, const ngl_rect_t *r);

/* Everything callers used to read straight out of the struct. */
int16_t ngl_surface_w(const ngl_surface_t *s);
int16_t ngl_surface_h(const ngl_surface_t *s);

/** The whole surface as a rect: {0, 0, w, h}. */
ngl_rect_t ngl_surface_bounds(const ngl_surface_t *s);

/** What draws are currently confined to, in surface coordinates. */
ngl_rect_t ngl_surface_clip(const ngl_surface_t *s);

/**
 * Read-only view of row @p y: ngl_surface_w() pixels, contiguous.
 *
 * The one way to get pixels back out of a surface, and deliberately a row at a
 * time - the stride stays ngl's business, so a caller that wants the whole
 * surface walks it. NULL if there is no such row. Nothing locks around this:
 * a reader sees whatever is in the buffer as it passes, which is what a
 * screenshot of a running app is anyway.
 */
const ngl_color_t *ngl_surface_row(const ngl_surface_t *s, int16_t y);

/* ------------------------------------------------------------------ */
/* Primitives                                                          */
/* ------------------------------------------------------------------ */

void ngl_clear(ngl_surface_t *s, ngl_color_t c);
void ngl_pixel(ngl_surface_t *s, int16_t x, int16_t y, ngl_color_t c);

/** Blend `c` over the pixel at (x,y). a: 0 = keep, 255 = replace. */
void ngl_pixel_blend(ngl_surface_t *s, int16_t x, int16_t y, ngl_color_t c, uint8_t a);

void ngl_fill_rect(ngl_surface_t *s, ngl_rect_t r, ngl_color_t c);
void ngl_draw_rect(ngl_surface_t *s, ngl_rect_t r, ngl_color_t c, int16_t thickness);

void ngl_fill_round_rect(ngl_surface_t *s, ngl_rect_t r, int16_t radius, ngl_color_t c);
void ngl_draw_round_rect(ngl_surface_t *s, ngl_rect_t r, int16_t radius, ngl_color_t c,
                        int16_t thickness);

void ngl_hline(ngl_surface_t *s, int16_t x, int16_t y, int16_t w, ngl_color_t c);
void ngl_vline(ngl_surface_t *s, int16_t x, int16_t y, int16_t h, ngl_color_t c);

/** Hard-edged line (Bresenham). Cheap; use for axis-ish lines and borders. */
void ngl_line(ngl_surface_t *s, int16_t x0, int16_t y0, int16_t x1, int16_t y1, ngl_color_t c);

/** Anti-aliased line (Xiaolin Wu). */
void ngl_line_aa(ngl_surface_t *s, int16_t x0, int16_t y0, int16_t x1, int16_t y1, ngl_color_t c);

/* ------------------------------------------------------------------ */
/* Blitting                                                            */
/* ------------------------------------------------------------------ */

/** Copy `src_rect` of `src` (NULL = all of it) to (x,y) in `dst`. */
void ngl_blit(ngl_surface_t *dst, int16_t x, int16_t y,
             const ngl_surface_t *src, const ngl_rect_t *src_rect);

/** As ngl_blit(), but pixels equal to `key` are left untouched. */
void ngl_blit_key(ngl_surface_t *dst, int16_t x, int16_t y,
                 const ngl_surface_t *src, const ngl_rect_t *src_rect, ngl_color_t key);

/**
 * Copy `src_rect` of `src` (NULL = all of it) into `dst_rect`, scaling to fit.
 *
 * Nearest-neighbour, so a 2x or 3x blow-up of something drawn at 224x288 comes
 * out as clean squares rather than a blur - which is what that sort of picture
 * wants. Non-integer factors work and look like nearest-neighbour looks.
 *
 * The P4's PPA does this over DMA when it can, and then the scale costs no CPU
 * at all: the interesting case is an emulator or a viewer that composes a small
 * frame in fast memory every frame and wants it on a 1280x720 panel, where the
 * software version would be a quarter of a million stores into PSRAM. The
 * software path is still there and still correct, so this always works - the
 * return value says whether the whole rectangle was covered, not which path
 * ran.
 *
 * False if nothing was drawn: an empty rectangle, a clip that excluded it, or
 * a surface that is not there. A partially clipped blit draws the visible part
 * and returns true.
 *
 * `src` may be an ngl_surface_wrap() of ordinary memory, which is the usual
 * way in - wrap the buffer the frame was composed in and hand it over.
 */
bool ngl_blit_scale(ngl_surface_t *dst, ngl_rect_t dst_rect,
                   const ngl_surface_t *src, const ngl_rect_t *src_rect);

/**
 * Blit 8-bit palette indices through `pal`, converting to RGB565 per pixel.
 *
 * @param src     w*h indices, `stride` of them per row (0 = w)
 * @param pal     256 colours; an index past the end of a shorter table is the
 *                caller's bug and reads whatever is behind it
 * @param key     an index to treat as transparent, or -1 for none
 *
 * Machines that draw in indices are the rule and not the exception - a tile
 * ROM, a paletted image, anything with a colour table that changes without the
 * picture changing - and every one of them converts index to pixel once per
 * pixel per frame. That loop belongs on this side: an app carries no copy of
 * it, and it is compiled once here rather than out of PSRAM in each app that
 * needed it.
 *
 * Takes a raw pointer rather than a surface because ngl surfaces are RGB565
 * throughout and there is no reason to make indices pretend otherwise.
 */
void ngl_blit_p8(ngl_surface_t *dst, int16_t x, int16_t y,
                const uint8_t *src, int16_t w, int16_t h, int16_t stride,
                const ngl_color_t *pal, int key);

/* ------------------------------------------------------------------ */
/* Straight to the panel                                               */
/* ------------------------------------------------------------------ */

/**
 * The panel's own size, which does not change when the screen rotates.
 *
 * ngl_screen() is the rotated, logical frame - 1280x720 in landscape. This is
 * the glass: 720x1280 always. Only something addressing the panel directly
 * needs it, which means only ngl_panel_scale().
 */
void ngl_panel_size(int16_t *w, int16_t *h);

/**
 * Scale @p src onto the panel itself, with no rotation and no back buffer.
 *
 * The escape hatch for one specific shape of program: something that composes
 * a small picture every frame and wants it large on the glass. The ordinary
 * path - ngl_blit_scale() then ngl_flush() - writes that picture large twice,
 * once into the back buffer and once again into the panel, and the second of
 * those is a rotation.
 *
 * The rotation is the expensive half, and by a long way. Measured on a Tab5 at
 * 720x960: the scale runs at 85 Mpixels/s and the 1:1 rotate that follows it
 * at 19. A 90 degree rotate writes a column where it read a row, so every
 * output pixel lands a panel row away from the last one and PSRAM never gets
 * to burst. Four and a half times the cost of the same pixels written in
 * order.
 *
 * So this does neither. @p dst_rect is in *panel* coordinates and the caller
 * is expected to have composed @p src already turned - which for a 4:3
 * playfield is a coordinate swap in the drawing helpers and costs nothing at
 * the size the picture is composed at. Turning 43,200 pixels on the way in is
 * free; turning 691,200 on the way out is 36 ms.
 *
 * @param mirror_x,mirror_y  reverse the source along that axis, which is how
 *        one composed picture serves both landscape rotations: NGL_ROT_270 is
 *        NGL_ROT_90 with both axes flipped, and a mirror still writes each row
 *        in order, so it costs nothing the way a rotate does.
 *
 * The destination scale must be a whole number of sixteenths of the source, as
 * for ngl_blit_scale(), and there is deliberately no software fallback: the
 * loop this would need writes a megabyte into the live framebuffer a pixel at
 * a time, and a caller that quietly got that instead would be slower than the
 * ordinary path it came here to avoid. False means "did nothing".
 *
 * Nothing is marked dirty and no flush is needed - this *is* the panel. What
 * it costs instead is that ngl's back buffer no longer matches the glass over
 * @p dst_rect, so anything that restores pixels from it - a modal panel
 * closing - will restore what was there before. A caller doing this owns the
 * repaint afterwards; neos_ui_busy() going false is the edge to watch.
 */
bool ngl_panel_scale(const ngl_surface_t *src, ngl_rect_t src_rect,
                    ngl_rect_t dst_rect, bool mirror_x, bool mirror_y);

/* ------------------------------------------------------------------ */
/* Text                                                                */
/* ------------------------------------------------------------------ */

/** Draw `str` with its top-left at (x,y). Returns the x after the last glyph. */
int16_t ngl_text(ngl_surface_t *s, int16_t x, int16_t y, const char *str,
                const ngl_font_t *f, ngl_color_t c);

/** As ngl_text(), but fills the glyph cells with `bg` first. */
int16_t ngl_text_bg(ngl_surface_t *s, int16_t x, int16_t y, const char *str,
                   const ngl_font_t *f, ngl_color_t c, ngl_color_t bg);

int16_t ngl_text_width(const ngl_font_t *f, const char *str);

/* ------------------------------------------------------------------ */
/* Icons                                                               */
/* ------------------------------------------------------------------ */

/** Draw `ic` at (x,y), tinted `c`, blended by its alpha. */
void ngl_icon(ngl_surface_t *s, int16_t x, int16_t y, const ngl_icon_t *ic, ngl_color_t c);

/**
 * Find an icon by name and pixel size, e.g. ngl_icon_find("bomb", 32).
 *
 * This is how apps get at icons: the individual objects are generated from
 * icons.json and are deliberately not part of the ABI, so that the icon set
 * can change without breaking apps already on a card. NULL if there is no
 * such icon at that size - draw nothing rather than guessing a substitute.
 */
const ngl_icon_t *ngl_icon_find(const char *name, int16_t px);

#ifdef __cplusplus
}
#endif
