/* GENERATED by tools/genicons/genicons.py - do not edit. */
#pragma once
#include "ngl.h"

extern const ngl_icon_t ngl_icon_smile_24;
extern const ngl_icon_t ngl_icon_smile_32;
extern const ngl_icon_t ngl_icon_dizzy_24;
extern const ngl_icon_t ngl_icon_dizzy_32;
extern const ngl_icon_t ngl_icon_bomb_24;
extern const ngl_icon_t ngl_icon_bomb_32;
extern const ngl_icon_t ngl_icon_close_24;
extern const ngl_icon_t ngl_icon_close_32;
extern const ngl_icon_t ngl_icon_battery_24;
extern const ngl_icon_t ngl_icon_battery_32;
extern const ngl_icon_t ngl_icon_wifi_24;
extern const ngl_icon_t ngl_icon_wifi_32;
extern const ngl_icon_t ngl_icon_settings_24;
extern const ngl_icon_t ngl_icon_settings_32;
extern const ngl_icon_t ngl_icon_clock_24;
extern const ngl_icon_t ngl_icon_clock_32;
extern const ngl_icon_t ngl_icon_folder_24;
extern const ngl_icon_t ngl_icon_folder_32;
extern const ngl_icon_t ngl_icon_home_24;
extern const ngl_icon_t ngl_icon_home_32;
extern const ngl_icon_t ngl_icon_back_24;
extern const ngl_icon_t ngl_icon_back_32;
